spring:
  application:
    name: cibaria
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
server:
  servlet:
    context-path: /api
